#!/usr/bin/env python3
"""Print the ignored-test ledger from Rust declarations; no files are modified."""
from pathlib import Path
import re
import json
import io
import sys
from collections import Counter

root = Path(__file__).resolve().parents[1]
registry = json.loads((root / "scripts/isolated-tests.json").read_text())
mapped = {entry[2].split("::")[-1] for entries in registry.values() for entry in entries}
output = io.StringIO()
original_stdout = sys.stdout
sys.stdout = output
rows = []
for path in sorted((root / "crates").rglob("*.rs")):
    source = path.read_text()
    for match in re.finditer(r'#\[ignore(?:\s*=\s*"([^"\n]*)")?\]', source):
        function = re.search(r'\b(?:async\s+)?fn\s+(\w+)', source[match.end():])
        if not function:
            raise RuntimeError(f"ignore without function: {path}")
        name = function.group(1)
        reason = match.group(1) or "subprocess helper; invoked by its parent test"
        relative = path.relative_to(root).as_posix()
        if "subprocess" in name or not match.group(1):
            tier, enable = "Helper", "Run parent unit/sandbox test; do not enable globally"
        elif "driver-tls-tests" in relative:
            tier, enable = "TLS", "scripts/test-driver-tls.sh"
        elif "release-tests" in relative:
            tier, enable = "Release", "scripts/test-postgres-release.sh"
        elif "socket" in relative:
            tier, enable = "Socket", "scripts/test-postgres-socket.sh"
        elif "smoke_local" in relative:
            tier, enable = "Smoke", "scripts/smoke-postgres.sh against disposable DB"
        elif "Secret Service" in reason or "secret" in relative:
            if name not in mapped:
                raise RuntimeError(f"unmapped keyring test: {name}")
            tier, enable = "Keyring", "scripts/test-secret-service.sh in isolated session"
        elif "isolated GTK display" in reason:
            if name not in mapped:
                raise RuntimeError(f"unmapped GTK test: {name}")
            tier, enable = "GTK", "scripts/test-gtk-widgets.sh"
        elif "docker" in reason.lower() and relative.startswith("crates/ssh/"):
            tier, enable = "Driver", f"Docker plus cargo test -p tablepro-ssh --test {path.stem} -- --include-ignored --test-threads=1"
        elif "docker" in reason.lower():
            engine = path.relative_to(root).parts[2]
            tier, enable = "Driver", f"Docker plus cargo test -p tablepro-driver-{engine} --test integration -- --include-ignored --test-threads=1"
        else:
            raise RuntimeError(f"unmapped ignored test: {relative}: {name}")
        rows.append((relative, name, tier, reason, enable))
print("# Ignored-test inventory\n")
print("Generated by `python3 scripts/inventory-ignored-tests.py` from the working tree.\n")
print("These attributes select an execution environment; helper attributes are not missing coverage. Keep fixture tests ignored in the ordinary unit tier. Enable them through their runner once its prerequisites exist.\n")
print(f"Total: {len(rows)} declarations. " + "; ".join(f"{k}: {v}" for k, v in sorted(Counter(r[2] for r in rows).items())) + ".\n")
print("| Test | Tier | Reason | Activation condition / runner |\n|---|---|---|---|")
for path, name, tier, reason, enable in rows:
    print(f"| [{name}](../{path}) | {tier} | {reason} | `{enable}` |")
sys.stdout = original_stdout
for name in mapped:
    if not any(row[1] == name for row in rows):
        raise RuntimeError(f"stale isolated-test registration: {name}")
if "--check" in sys.argv:
    if (root / "docs/ignored-tests.md").read_text() != output.getvalue():
        raise SystemExit("ignored-test inventory stale: regenerate scripts/inventory-ignored-tests.py")
    print("ignored-test inventory and isolated registrations: OK")
else:
    print(output.getvalue(), end="")
