use super::*;

#[tokio::test]
#[ignore = "requires docker"]
async fn a_batch_reports_rollback_failure_after_postgres_terminates_its_backend() {
    let (_container, mut options) = start_pg().await;
    let application_name = format!("bookie_rollback_failure_{}", Uuid::new_v4());
    options.application_name = Some(application_name.clone());
    let connection = Arc::new(connect(options.clone()).await);
    let mut observer_options = options;
    observer_options.application_name = Some(format!("{application_name}_observer"));
    let observer = connect(observer_options).await;
    connection
        .execute(
            "CREATE TABLE rollback_failure_probe (\
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY\
            )",
        )
        .await
        .expect("create rollback probe with a non-transactional identity sequence");
    connection
        .execute("CREATE TABLE rollback_failure_trigger_effects (parent_id integer, allocated_id bigint)")
        .await
        .expect("create transactional trigger effect table");
    connection
        .execute("CREATE SEQUENCE rollback_failure_trigger_sequence")
        .await
        .expect("create non-transactional trigger sequence");
    connection
        .execute(
            "CREATE FUNCTION rollback_failure_probe_trigger() RETURNS trigger \
             LANGUAGE plpgsql AS $$ BEGIN \
             INSERT INTO rollback_failure_trigger_effects VALUES \
             (NEW.id, nextval('rollback_failure_trigger_sequence')); \
             RETURN NEW; END $$",
        )
        .await
        .expect("create trigger function");
    connection
        .execute(
            "CREATE TRIGGER rollback_failure_probe_after_insert \
             AFTER INSERT ON rollback_failure_probe FOR EACH ROW \
             EXECUTE FUNCTION rollback_failure_probe_trigger()",
        )
        .await
        .expect("create trigger that writes transactionally and advances a sequence");

    let executing = connection.clone();
    let batch = vec![
        ("INSERT INTO rollback_failure_probe DEFAULT VALUES".into(), Vec::new()),
        ("SELECT pg_sleep(60)".into(), Vec::new()),
    ];
    let operation = tokio::spawn(async move { executing.execute_in_transaction(&batch).await });
    let pid = tokio::time::timeout(std::time::Duration::from_secs(15), async {
        loop {
            let activity = observer
                .query(&format!(
                    "SELECT pid::bigint FROM pg_stat_activity \
                     WHERE application_name = '{application_name}' \
                       AND state = 'active' AND query LIKE '%pg_sleep(60)%' LIMIT 1"
                ))
                .await
                .expect("observe active transaction statement");
            if let Some(Value::Int(pid)) = activity.rows.first().and_then(|row| row.first()) {
                break *pid;
            }
            tokio::time::sleep(std::time::Duration::from_millis(50)).await;
        }
    })
    .await
    .expect("batch reached its blocking PostgreSQL statement");

    let terminated = observer
        .query(&format!("SELECT pg_terminate_backend({pid})"))
        .await
        .expect("terminate the transaction backend");
    assert_eq!(terminated.rows, vec![vec![Value::Bool(true)]]);

    let error = tokio::time::timeout(std::time::Duration::from_secs(15), operation)
        .await
        .expect("batch exits after backend termination")
        .expect("batch task")
        .expect_err("the failed statement and rollback must be reported");
    match error {
        DriverError::TransactionRollbackFailed {
            statement_index,
            source,
            rollback_error,
        } => {
            assert_eq!(statement_index, 1);
            assert!(matches!(source.as_ref(), DriverError::Disconnected), "{source:?}");
            assert!(
                matches!(rollback_error.as_ref(), DriverError::Disconnected),
                "{rollback_error:?}"
            );
        }
        other => panic!("expected rollback failure with unknown outcome, got {other:?}"),
    }

    let persisted = connection
        .query("SELECT count(*)::bigint FROM rollback_failure_probe")
        .await
        .expect("query after the terminated connection was discarded");
    assert_eq!(persisted.rows, vec![vec![Value::Int(0)]]);
    let trigger_rows = connection
        .query("SELECT count(*)::bigint FROM rollback_failure_trigger_effects")
        .await
        .expect("query trigger side effects after the terminated connection was discarded");
    assert_eq!(
        trigger_rows.rows,
        vec![vec![Value::Int(0)]],
        "the trigger's transactional table write must roll back"
    );

    // PostgreSQL sequence increments are not rolled back with the row. This
    // makes the boundary explicit: the transaction's table write disappeared,
    // while the identity allocation is still consumed.
    let sequence = connection
        .query("SELECT last_value::bigint, is_called FROM rollback_failure_probe_id_seq")
        .await
        .expect("query the identity sequence after backend termination");
    assert_eq!(sequence.rows, vec![vec![Value::Int(1), Value::Bool(true)]]);
    let trigger_sequence = connection
        .query("SELECT last_value::bigint, is_called FROM rollback_failure_trigger_sequence")
        .await
        .expect("query the trigger sequence after backend termination");
    assert_eq!(
        trigger_sequence.rows,
        vec![vec![Value::Int(1), Value::Bool(true)]],
        "the trigger's sequence allocation is not rolled back"
    );
}
